stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

build_job:
  stage: build
  image: openjdk:17-jdk
  script:
    - chmod +x gradlew
    - ./gradlew build
test_job:
  stage: test
  image: openjdk:17-jdk
  script:
    - chmod +x gradlew
    - ./gradlew test