stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

build_job:
  stage: build
  image: eclipse-temurin:17-alpine
  script:
    - chmod +x gradlew
    - ./gradlew build --no-daemon

test_job:
  stage: test
  image: eclipse-temurin:17-alpine
  script:
    - chmod +x gradlew
    - ./gradlew test --no-daemon
